apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: techchallenger
spec:
  type: NodePort
  selector:
    app: evaluation-service
  ports:
    - port: 8004
      targetPort: 8004
      nodePort: 30084
