apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: techchallenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          image: robertoribeiroo/flag-service:latest
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: postgres://flags_user:flags_pass@flags-postgres:5432/flags_db
            - name: PORT
              value: "8002"
            - name: AUTH_SERVICE_URL
              value: http://auth-service:8001
---
apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: techchallenger
spec:
  selector:
    app: flag-service
  ports:
    - port: 8002