apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: techchallenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: docker.io/robertoribeiroo/auth-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: postgres://auth_user:auth_pass_123@auth-postgres.cngcg0y0s735.us-east-1.rds.amazonaws.com:5432/auth_db
            - name: PORT
              value: "8001"
            - name: MASTER_KEY
              value: admin-secreto-123
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: techchallenger
spec:
  selector:
    app: auth-service
  ports:
    - port: 8001
      targetPort: 8001

