apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: techchallenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: docker.io/robertoribeiroo/evaluation-service:latest
          ports:
            - containerPort: 8004
          env:
            - name: PORT
              value: "8004"
            - name: REDIS_URL
              value: redis://clustercfg.techchallenger-redis.mvwnsq.use1.cache.amazonaws.com:6379
            - name: FLAG_SERVICE_URL
              value: http://flag-service:8002
            - name: TARGETING_SERVICE_URL
              value: http://targeting-service:8003
            - name: AUTH_SERVICE_URL
              value: http://auth-service:8001
            - name: SERVICE_API_KEY
              value: tm_key_715e0de7954245cb6710f4a11b3e3751c24ee5a254c3e4878964ae7d34d74f34
            - name: AWS_SQS_URL
              value: https://sqs.us-east-1.amazonaws.com/242686594219/techchallenger-evaluation-events
            - name: AWS_REGION
              value: us-east-1
            - name: DYNAMODB_TABLE
              value: techchallenger-analytics




---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: techchallenger
spec:
  selector:
    app: evaluation-service
  ports:
    - port: 8004
      targetPort: 8004

