apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: techchallenger
data:
  PORT: "8004"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  AUTH_SERVICE_URL: "http://auth-service:8001"
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/007188159471/techchallenger-evaluation-events"
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: techchallenger
type: Opaque
stringData:
  REDIS_URL: "redis://techchallenger-redis.pctckz.0001.use1.cache.amazonaws.com:6379"
  SERVICE_API_KEY: "tm_key_8582ecdb17fe2ede8097c697436117791342e7abafe76c78dab73c2fb98afe32"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: techchallenger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 007188159471.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:latest
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: evaluation-service-config
            - secretRef:
                name: evaluation-service-secret
          resources:
            requests:
              cpu: 150m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: techchallenger
spec:
  selector:
    app: evaluation-service
  ports:
    - port: 8004
      targetPort: 8004
